sudo: false
language: node_js
node_js:
- stable
- 4
install: npm update
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: knpcsAAH+qj3raB+sKyFwkowaqRbDRIBdSTgCKWxjja3StNkn6xkfnxbnNCNBdDRKTj88ipEvywnFD7Tx80o0Jgd8eUDDfMek6TBbPOVur1Q66MCyXBy7LVp/pFVDuCOWmhxgWWHp0R4f1MLxrXApBYIZJbAe2HBpTJZVPfmZ8tHJQZs5lYnBlhynK8vqXaG7mneW/eUgs3IF5A5DXKB9/5gI0yYGvj0i+GF5VR0on7TycKJwkY8WH752oVTbytjdLnQixvpADhieufecjpMFVVozuwEBfH4R3eVeGyAmttnBKnKjykOFC0ohPdTWjf7UlfcOKYuyv0JX1JqWKUig41v3AczoRacI3vM5DTu3JTYZUnTttv4C1zmf6tqdcP95Q2SYrZDY9yDT7HnDrrgSKotcJPof+y8WrD+IAYUclckXKK1mvzu3qfUJkq/fkP7jwnN2TKKEBiKmB2eCYWpipZ0mPh38isfl5Ra/ocyIc/4W0M1ki48pkIcNXinuwederjWLyr4SIwdJGQrAkfXRI/iRxdIpW9ZojYccjje992mhs7vnT6PQLOQb4NAMeyACJmM/+8rHd89zTpNPerDnvRsC0SmZkduZql/YO9+grz7g9wlDI5A5/4cZqQDEpef3ColVe5CsHihI/l6Ky76j59gdwN4Ixrc5aozjniiEhc=
  on:
    tags: true
    repo: makojs/stat
    node: stable
